image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
stages:
- build
- deploy

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

ttd_build_job:
  stage: build
  script:
  - echo $CI_PIPELINE_ID
  - docker build -f DockerfileApp -t iiuaui:build$CI_PIPELINE_ID .

ttd_deploy_job:
  stage: deploy
  script:
  - echo $CI_PIPELINE_ID
  - docker top iiua && docker stop iiua && docker rm iiua
 #- docker-compose up -d
  - docker run -d  --name iiuaui --env VIRTUAL_HOST=masterui.alexduxa.online --env VIRTUAL_PORT=4200  --restart=always iiuaui:build$CI_PIPELINE_ID
