version: "3.2"

services:
  iiua-prod-ui:
    container_name: iiua-prod-ui
    image: registry.iiua.com.ua:5000/iiua:prod-ui-latest
    volumes:
      - /opt/docker/hostfiles/iiua/ui/logs:/app/logs
    restart: always
    environment:      
      - ASPNETCORE_ENVIRONMENT=MASTER
      - Projects__Auth__MySQL
      - Projects__Projects__MySQL
      - Projects__Files__MySQL
      - Projects__Maps__MongoDB__ConnectionString
      - Projects__Maps__MongoDB__MongoDatabase 
    network_mode: bridge


